AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  smarthomejs:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: smarthome_js
      Description: ''
      Handler: index.handler
      MemorySize: 128
      Role: 'arn:aws:iam::066480080978:role/service-role/smarthome_js-role-hklvpoqa'
      Runtime: nodejs12.x
      Timeout: 3
